### ISSUE TITLE
Not able to Connect

### ISSUE THREAD

**Issue by Lenni** [surferran/toys#1]
If I try to connect my Spyrit MAX2 (which is a rebranded Version of the Syma X5C-1) the Drone doesn't tell me its connected. Here is ther Output of the Serial Monitor:
`Opening port
Port open
initial protocol is for : 1_ remote test on . Virtual Transmiter ID : 121255255255
control by : 
 up   arrow - go up (inc throttel),
 down arrow - go down(dec throttel) 
 left arrow - yaw left(alleron-),
 right arrow - yaw right(aleron+) 
 'w'        - pitch up(elevetor-),
 'z' - pitch down(elevetor+) 
 'a'        - roll left(rudder-),
 's' - roll right(rudder+) 
pcb status 1 : 0
pcb status 2 : 0
done init & bind protocol
done reset`

I hope you can help me, because I have no Idea what I am doing wrong. I can also add the SPI Communication between the Processor and the RF Module of the original Remote, which can connect to the Drone.

**Comment by surferran** [comment]
hello
i'm very sorry i didn't comment on your question before. i didn't see it. 
i now saw email about closing the issue, by chance , and i looked and saw the question above. 
i hope you closed it because you found a solution to your question or the task you're looking for.
thank you for downloading the code and trying it.
best regards,
Ran

**Comment by Lenni** [comment]
Yeah, i solved the Issue myself.
I also opened a repository for my Remote control. If you're interested have a look :D

**Comment by surferran** [comment]
nice.
thank you alot for your review. i looked at your repository. it looks very documented. i will try that.
i remember i had issue with my program to operate the quadrotor correctly for the right/left directions, while i think the simple up/down commands were fine. so i guess you set this up somehow .
